
import { Character } from './types';

export const VOWELS: Character[] = [
  { hangul: 'ㅏ', name: '아', transcription: { ru: 'а', en: 'a' }, type: 'vowel', soundVariations: [{ position: { ru: 'Везде', en: 'Everywhere' }, sound: { ru: 'а', en: 'a' }, exampleHangul: '아이', exampleTranscription: { ru: 'аи', en: 'ai' }, explanation: { ru: 'Открытый звук "а", как в слове "папа".', en: 'An open "a" sound, like in the word "father".' } }], acceptablePronunciations: ['아'] },
  { hangul: 'ㅑ', name: '야', transcription: { ru: 'я', en: 'ya' }, type: 'vowel', soundVariations: [{ position: { ru: 'Везде', en: 'Everywhere' }, sound: { ru: 'я', en: 'ya' }, exampleHangul: '야구', exampleTranscription: { ru: 'ягу', en: 'yagu' }, explanation: { ru: 'Йотированный звук "я", как в слове "яма".', en: 'A yotated "ya" sound, like in the word "yard".' } }], acceptablePronunciations: ['야'] },
  { hangul: 'ㅓ', name: '어', transcription: { ru: 'о', en: 'eo' }, type: 'vowel', soundVariations: [{ position: { ru: 'Везде', en: 'Everywhere' }, sound: { ru: 'о', en: 'eo' }, exampleHangul: '어머니', exampleTranscription: { ru: 'омони', en: 'eomeoni' }, explanation: { ru: 'Более открытый звук "о", средний между "о" и "а". Похож на звук "u" в слове "cup".', en: 'A more open "o" sound, between "o" and "a". Similar to the "u" sound in "cup".' } }], acceptablePronunciations: ['어'] },
  { hangul: 'ㅕ', name: '여', transcription: { ru: 'ё', en: 'yeo' }, type: 'vowel', soundVariations: [{ position: { ru: 'Везде', en: 'Everywhere' }, sound: { ru: 'ё', en: 'yeo' }, exampleHangul: '여기', exampleTranscription: { ru: 'ёги', en: 'yeogi' }, explanation: { ru: 'Йотированный звук "ё".', en: 'A yotated "yeo" sound.' } }], acceptablePronunciations: ['여'] },
  { hangul: 'ㅗ', name: '오', transcription: { ru: 'о', en: 'o' }, type: 'vowel', soundVariations: [{ position: { ru: 'Везде', en: 'Everywhere' }, sound: { ru: 'о', en: 'o' }, exampleHangul: '오이', exampleTranscription: { ru: 'ои', en: 'oi' }, explanation: { ru: 'Более закрытый, "огубленный" звук "о", как в "вода".', en: 'A more closed, rounded "o" sound, like in "boat".' } }], acceptablePronunciations: ['오'] },
  { hangul: 'ㅛ', name: '요', transcription: { ru: 'ё', en: 'yo' }, type: 'vowel', soundVariations: [{ position: { ru: 'Везде', en: 'Everywhere' }, sound: { ru: 'ё', en: 'yo' }, exampleHangul: '요리', exampleTranscription: { ru: 'ёри', en: 'yori' }, explanation: { ru: 'Йотированный огубленный звук "ё".', en: 'A yotated, rounded "yo" sound.' } }], acceptablePronunciations: ['요'] },
  { hangul: 'ㅜ', name: '우', transcription: { ru: 'у', en: 'u' }, type: 'vowel', soundVariations: [{ position: { ru: 'Везде', en: 'Everywhere' }, sound: { ru: 'у', en: 'u' }, exampleHangul: '우리', exampleTranscription: { ru: 'ури', en: 'uri' }, explanation: { ru: 'Звук "у", как в слове "утро".', en: 'A "u" sound, like in the word "moon".' } }], acceptablePronunciations: ['우'] },
  { hangul: 'ㅠ', name: '유', transcription: { ru: 'ю', en: 'yu' }, type: 'vowel', soundVariations: [{ position: { ru: 'Везде', en: 'Everywhere' }, sound: { ru: 'ю', en: 'yu' }, exampleHangul: '유리', exampleTranscription: { ru: 'юри', en: 'yuri' }, explanation: { ru: 'Йотированный звук "ю", как в слове "юла".', en: 'A yotated "yu" sound, like in the word "you".' } }], acceptablePronunciations: ['유'] },
  { hangul: 'ㅡ', name: '으', transcription: { ru: 'ы', en: 'eu' }, type: 'vowel', soundVariations: [{ position: { ru: 'Везде', en: 'Everywhere' }, sound: { ru: 'ы', en: 'eu' }, exampleHangul: '으악', exampleTranscription: { ru: 'ыак', en: 'euak' }, explanation: { ru: 'Звук "ы", произносится с растянутыми губами.', en: 'An "eu" sound, pronounced with lips spread wide.' } }], acceptablePronunciations: ['으'] },
  { hangul: 'ㅣ', name: '이', transcription: { ru: 'и', en: 'i' }, type: 'vowel', soundVariations: [{ position: { ru: 'Везде', en: 'Everywhere' }, sound: { ru: 'и', en: 'i' }, exampleHangul: '이유', exampleTranscription: { ru: 'ию', en: 'iyu' }, explanation: { ru: 'Звук "и", как в слове "мир".', en: 'An "i" sound, like in the word "see".' } }], acceptablePronunciations: ['이'] },
];

export const DIPHTHONGS: Character[] = [
  { hangul: 'ㅐ', name: '애', transcription: { ru: 'э', en: 'ae' }, type: 'vowel', soundVariations: [{ position: { ru: 'Везде', en: 'Everywhere' }, sound: { ru: 'э', en: 'ae' }, exampleHangul: '개', exampleTranscription: { ru: 'кэ', en: 'gae' }, explanation: { ru: 'Открытый звук "э", как в слове "этот".', en: 'An open "ae" sound, like in the word "cat".' } }], acceptablePronunciations: ['애'] },
  { hangul: 'ㅒ', name: '얘', transcription: { ru: 'е', en: 'yae' }, type: 'vowel', soundVariations: [{ position: { ru: 'Везде', en: 'Everywhere' }, sound: { ru: 'е', en: 'yae' }, exampleHangul: '얘기', exampleTranscription: { ru: 'еги', en: 'yaegi' }, explanation: { ru: 'Йотированный звук "е", как в слове "ель".', en: 'A yotated "yae" sound, like in "yell".' } }], acceptablePronunciations: ['얘'] },
  { hangul: 'ㅔ', name: '에', transcription: { ru: 'е', en: 'e' }, type: 'vowel', soundVariations: [{ position: { ru: 'Везде', en: 'Everywhere' }, sound: { ru: 'е', en: 'e' }, exampleHangul: '게', exampleTranscription: { ru: 'ке', en: 'ge' }, explanation: { ru: 'Более закрытый звук "е". В современном корейском почти не отличается от ㅐ.', en: 'A more closed "e" sound. In modern Korean, it\'s nearly indistinguishable from ㅐ.' } }], acceptablePronunciations: ['에'] },
  { hangul: 'ㅖ', name: '예', transcription: { ru: 'е', en: 'ye' }, type: 'vowel', soundVariations: [{ position: { ru: 'Везде', en: 'Everywhere' }, sound: { ru: 'е', en: 'ye' }, exampleHangul: '예', exampleTranscription: { ru: 'е', en: 'ye' }, explanation: { ru: 'Йотированный звук "е". В начале слова читается как "е", после согласных - как "е".', en: 'A yotated "ye" sound. Pronounced as "ye" at the start of a word, and as "e" after a consonant.' } }], acceptablePronunciations: ['예'] },
  { hangul: 'ㅘ', name: '와', transcription: { ru: 'ва', en: 'wa' }, type: 'vowel', soundVariations: [{ position: { ru: 'Везде', en: 'Everywhere' }, sound: { ru: 'ва', en: 'wa' }, exampleHangul: '과자', exampleTranscription: { ru: 'квачжа', en: 'gwaja' }, explanation: { ru: 'Сочетание "о" + "а".', en: 'A combination of "o" + "a".' } }], acceptablePronunciations: ['와'] },
  { hangul: 'ㅙ', name: '왜', transcription: { ru: 'вэ', en: 'wae' }, type: 'vowel', soundVariations: [{ position: { ru: 'Везде', en: 'Everywhere' }, sound: { ru: 'вэ', en: 'wae' }, exampleHangul: '왜', exampleTranscription: { ru: 'вэ', en: 'wae' }, explanation: { ru: 'Сочетание "о" + "э".', en: 'A combination of "o" + "ae".' } }], acceptablePronunciations: ['왜'] },
  { hangul: 'ㅚ', name: '외', transcription: { ru: 'ве', en: 'oe' }, type: 'vowel', soundVariations: [{ position: { ru: 'Везде', en: 'Everywhere' }, sound: { ru: 'ве', en: 'oe' }, exampleHangul: '외국', exampleTranscription: { ru: 'вегук', en: 'oeguk' }, explanation: { ru: 'Сочетание "о" + "и", произносится как "ве".', en: 'A combination of "o" + "i", pronounced like "we" in "wet".' } }], acceptablePronunciations: ['외'] },
  { hangul: 'ㅝ', name: '워', transcription: { ru: 'во', en: 'wo' }, type: 'vowel', soundVariations: [{ position: { ru: 'Везде', en: 'Everywhere' }, sound: { ru: 'во', en: 'wo' }, exampleHangul: '뭐', exampleTranscription: { ru: 'мво', en: 'mwo' }, explanation: { ru: 'Сочетание "у" + "о".', en: 'A combination of "u" + "eo".' } }], acceptablePronunciations: ['워'] },
  { hangul: 'ㅞ', name: '웨', transcription: { ru: 'ве', en: 'we' }, type: 'vowel', soundVariations: [{ position: { ru: 'Везде', en: 'Everywhere' }, sound: { ru: 'ве', en: 'we' }, exampleHangul: '웨딩', exampleTranscription: { ru: 'вединъ', en: 'weding' }, explanation: { ru: 'Сочетание "у" + "е".', en: 'A combination of "u" + "e".' } }], acceptablePronunciations: ['웨'] },
  { hangul: 'ㅟ', name: '위', transcription: { ru: 'ви', en: 'wi' }, type: 'vowel', soundVariations: [{ position: { ru: 'Везде', en: 'Everywhere' }, sound: { ru: 'ви', en: 'wi' }, exampleHangul: '쥐', exampleTranscription: { ru: 'чви', en: 'jwi' }, explanation: { ru: 'Сочетание "у" + "и".', en: 'A combination of "u" + "i".' } }], acceptablePronunciations: ['위'] },
  { hangul: 'ㅢ', name: '의', transcription: { ru: 'ый/и/е', en: 'ui/i/e' }, type: 'vowel', soundVariations: [
    { position: { ru: 'В начале слова', en: 'At the start of a word' }, sound: { ru: 'ый', en: 'ui' }, exampleHangul: '의사', exampleTranscription: { ru: 'ыйса', en: 'uisa' }, explanation: { ru: 'Читается как "ый".', en: 'Pronounced as "ui".' } },
    { position: { ru: 'В середине/конце слова', en: 'In the middle/end of a word' }, sound: { ru: 'и', en: 'i' }, exampleHangul: '편의점', exampleTranscription: { ru: 'пхёничжом', en: 'pyeonuijeom' }, explanation: { ru: 'Читается как "и".', en: 'Pronounced as "i".' } },
    { position: { ru: 'Как показатель падежа', en: 'As a possessive particle' }, sound: { ru: 'е', en: 'e' }, exampleHangul: '나의', exampleTranscription: { ru: 'нае', en: 'nae' }, explanation: { ru: 'Читается как "е".', en: 'Pronounced as "e".' } },
  ], acceptablePronunciations: ['의'] },
];

export const CONSONANTS: Character[] = [
    { hangul: 'ㄱ', name: '기역', transcription: { ru: 'к/г', en: 'g/k' }, type: 'consonant', soundVariations: [
      { position: { ru: 'В начале/конце слога', en: 'At the start/end of a syllable' }, sound: { ru: 'к', en: 'k' }, exampleHangul: '가구 / 국', exampleTranscription: { ru: 'кагу / кук', en: 'gagu / guk' }, explanation: { ru: 'В начале и конце слога произносится как глухой "к".', en: 'At the start and end of a syllable, it is an unaspirated "k".' } },
      { position: { ru: 'Между гласными', en: 'Between vowels' }, sound: { ru: 'г', en: 'g' }, exampleHangul: '아가', exampleTranscription: { ru: 'ага', en: 'aga' }, explanation: { ru: 'Между гласными озвончается и читается как "г".', en: 'Between vowels, it becomes voiced and sounds like "g".' } },
    ], acceptablePronunciations: ['기역', '가', '그'] },
    { hangul: 'ㄴ', name: '니은', transcription: { ru: 'н', en: 'n' }, type: 'consonant', soundVariations: [
      { position: { ru: 'Везде', en: 'Everywhere' }, sound: { ru: 'н', en: 'n' }, exampleHangul: '누나 / 안', exampleTranscription: { ru: 'нуна / ан', en: 'nuna / an' }, explanation: { ru: 'Всегда читается как "н".', en: 'Always pronounced as "n".' } },
    ], acceptablePronunciations: ['니은', '나', '느'] },
    { hangul: 'ㄷ', name: '디귿', transcription: { ru: 'т/д', en: 'd/t' }, type: 'consonant', soundVariations: [
      { position: { ru: 'В начале/конце слога', en: 'At the start/end of a syllable' }, sound: { ru: 'т', en: 't' }, exampleHangul: '다리 / 닫다', exampleTranscription: { ru: 'тари / татта', en: 'dari / datda' }, explanation: { ru: 'В начале и конце слога произносится как глухой "т".', en: 'At the start and end of a syllable, it is an unaspirated "t".' } },
      { position: { ru: 'Между гласными', en: 'Between vowels' }, sound: { ru: 'д', en: 'd' }, exampleHangul: '바다', exampleTranscription: { ru: 'пада', en: 'bada' }, explanation: { ru: 'Между гласными озвончается и читается как "д".', en: 'Between vowels, it becomes voiced and sounds like "d".' } },
    ], acceptablePronunciations: ['디귿', '다', '드'] },
    { hangul: 'ㄹ', name: '리을', transcription: { ru: 'р/ль', en: 'r/l' }, type: 'consonant', soundVariations: [
      { position: { ru: 'В начале слова и между гласными', en: 'At the start of a word and between vowels' }, sound: { ru: 'р', en: 'r' }, exampleHangul: '라디오 / 우리', exampleTranscription: { ru: 'радио / ури', en: 'radio / uri' }, explanation: { ru: 'Звучит как нечто среднее между "р" и "л".', en: 'Sounds like a flap, similar to a Spanish "r".' } },
      { position: { ru: 'В конце слога (патчим)', en: 'At the end of a syllable (batchim)' }, sound: { ru: 'ль', en: 'l' }, exampleHangul: '말', exampleTranscription: { ru: 'маль', en: 'mal' }, explanation: { ru: 'В конце слога читается как "ль".', en: 'At the end of a syllable, it sounds like "l".' } },
    ], acceptablePronunciations: ['리을', '라', '르'] },
    { hangul: 'ㅁ', name: '미음', transcription: { ru: 'м', en: 'm' }, type: 'consonant', soundVariations: [
      { position: { ru: 'Везде', en: 'Everywhere' }, sound: { ru: 'м', en: 'm' }, exampleHangul: '엄마 / 몸', exampleTranscription: { ru: 'омма / мом', en: 'eomma / mom' }, explanation: { ru: 'Всегда читается как "м".', en: 'Always pronounced as "m".' } },
    ], acceptablePronunciations: ['미음', '마', '므'] },
    { hangul: 'ㅂ', name: '비읍', transcription: { ru: 'п/б', en: 'b/p' }, type: 'consonant', soundVariations: [
      { position: { ru: 'В начале/конце слога', en: 'At the start/end of a syllable' }, sound: { ru: 'п', en: 'p' }, exampleHangul: '바보 / 밥', exampleTranscription: { ru: 'пабо / пап', en: 'babo / bap' }, explanation: { ru: 'В начале и конце слога произносится как глухой "п".', en: 'At the start and end of a syllable, it is an unaspirated "p".' } },
      { position: { ru: 'Между гласными', en: 'Between vowels' }, sound: { ru: 'б', en: 'b' }, exampleHangul: '나비', exampleTranscription: { ru: 'наби', en: 'nabi' }, explanation: { ru: 'Между гласными озвончается и читается как "б".', en: 'Between vowels, it becomes voiced and sounds like "b".' } },
    ], acceptablePronunciations: ['비읍', '바', '브'] },
    { hangul: 'ㅅ', name: '시옷', transcription: { ru: 'с/щ/т', en: 's/sh/t' }, type: 'consonant', soundVariations: [
      { position: { ru: 'Перед большинством гласных', en: 'Before most vowels' }, sound: { ru: 'с', en: 's' }, exampleHangul: '사람', exampleTranscription: { ru: 'сарам', en: 'saram' }, explanation: { ru: 'Читается как "с".', en: 'Pronounced as "s".' } },
      { position: { ru: 'Перед ㅣ, ㅑ, ㅕ, ㅛ, ㅠ...', en: 'Before ㅣ, ㅑ, ㅕ, ㅛ, ㅠ...' }, sound: { ru: 'щ', en: 'sh' }, exampleHangul: '시간', exampleTranscription: { ru: 'щиган', en: 'sigan' }, explanation: { ru: 'Читается как мягкий "щ".', en: 'Pronounced as a soft "sh".' } },
      { position: { ru: 'В конце слога (патчим)', en: 'At the end of a syllable (batchim)' }, sound: { ru: 'т', en: 't' }, exampleHangul: '옷', exampleTranscription: { ru: 'от', en: 'ot' }, explanation: { ru: 'В конце слога оглушается до "т".', en: 'At the end of a syllable, it is pronounced as "t".' } },
    ], acceptablePronunciations: ['시옷', '사', '스'] },
    { hangul: 'ㅇ', name: '이응', transcription: { ru: 'нет звука/н', en: 'silent/ng' }, type: 'consonant', soundVariations: [
      { position: { ru: 'В начале слога', en: 'At the start of a syllable' }, sound: { ru: 'нет звука', en: 'silent' }, exampleHangul: '아이', exampleTranscription: { ru: 'аи', en: 'ai' }, explanation: { ru: 'В начале слога перед гласной не читается, служит как "пустой" согласный.', en: 'Before a vowel at the start of a syllable, it is a silent placeholder.' } },
      { position: { ru: 'В конце слога (патчим)', en: 'At the end of a syllable (batchim)' }, sound: { ru: 'н (носовое)', en: 'ng' }, exampleHangul: '강', exampleTranscription: { ru: 'канъ', en: 'gang' }, explanation: { ru: 'В конце слога читается как носовой звук "н" (английское "ng").', en: 'At the end of a syllable, it is pronounced as a nasal "ng" sound, like in "sing".' } },
    ], acceptablePronunciations: ['이응'] },
    { hangul: 'ㅈ', name: '지읒', transcription: { ru: 'ч/дж/т', en: 'j/t' }, type: 'consonant', soundVariations: [
        { position: { ru: 'В начале слова', en: 'At the start of a word' }, sound: { ru: 'ч', en: 'j' }, exampleHangul: '자다', exampleTranscription: { ru: 'чада', en: 'jada' }, explanation: { ru: 'В начале слова произносится как "ч".', en: 'At the start of a word, it is an unaspirated "j".' } },
        { position: { ru: 'Между гласными', en: 'Between vowels' }, sound: { ru: 'дж', en: 'j' }, exampleHangul: '오징어', exampleTranscription: { ru: 'оджинъо', en: 'ojingeo' }, explanation: { ru: 'Между гласными озвончается.', en: 'Between vowels, it becomes voiced.' } },
        { position: { ru: 'В конце слога (патчим)', en: 'At the end of a syllable (batchim)' }, sound: { ru: 'т', en: 't' }, exampleHangul: '낮', exampleTranscription: { ru: 'нат', en: 'nat' }, explanation: { ru: 'В конце слога оглушается до "т".', en: 'At the end of a syllable, it is pronounced as "t".' } },
    ], acceptablePronunciations: ['지읒', '자', '즈'] },
    { hangul: 'ㅊ', name: '치읓', transcription: { ru: 'чх/т', en: 'ch/t' }, type: 'consonant', soundVariations: [
        { position: { ru: 'В начале и середине слова', en: 'At the start and middle of a word' }, sound: { ru: 'чх', en: 'ch' }, exampleHangul: '차', exampleTranscription: { ru: 'чха', en: 'cha' }, explanation: { ru: 'Придыхательный "чх". Произносится с сильным выдохом.', en: 'An aspirated "ch" sound, pronounced with a strong puff of air.' } },
        { position: { ru: 'В конце слога (патчим)', en: 'At the end of a syllable (batchim)' }, sound: { ru: 'т', en: 't' }, exampleHangul: '꽃', exampleTranscription: { ru: 'ккот', en: 'kkot' }, explanation: { ru: 'В конце слога оглушается до "т".', en: 'At the end of a syllable, it is pronounced as "t".' } },
    ], acceptablePronunciations: ['치읓', '차', '츠'] },
    { hangul: 'ㅋ', name: '키읔', transcription: { ru: 'кх', en: 'k' }, type: 'consonant', soundVariations: [
        { position: { ru: 'В начале и середине слова', en: 'At the start and middle of a word' }, sound: { ru: 'кх', en: 'k' }, exampleHangul: '크다', exampleTranscription: { ru: 'кхыда', en: 'keuda' }, explanation: { ru: 'Придыхательный "кх". Произносится с сильным выдохом.', en: 'An aspirated "k" sound, pronounced with a strong puff of air.' } },
        { position: { ru: 'В конце слога (патчим)', en: 'At the end of a syllable (batchim)' }, sound: { ru: 'к', en: 'k' }, exampleHangul: '부엌', exampleTranscription: { ru: 'пуок', en: 'bueok' }, explanation: { ru: 'В конце слога оглушается до "к".', en: 'At the end of a syllable, it is pronounced as "k".' } },
    ], acceptablePronunciations: ['키읔', '카', '크'] },
    { hangul: 'ㅌ', name: '티읕', transcription: { ru: 'тх', en: 't' }, type: 'consonant', soundVariations: [
        { position: { ru: 'В начале и середине слова', en: 'At the start and middle of a word' }, sound: { ru: 'тх', en: 't' }, exampleHangul: '토마토', exampleTranscription: { ru: 'тхоматхо', en: 'tomato' }, explanation: { ru: 'Придыхательный "тх". Произносится с сильным выдохом.', en: 'An aspirated "t" sound, pronounced with a strong puff of air.' } },
        { position: { ru: 'В конце слога (патчим)', en: 'At the end of a syllable (batchim)' }, sound: { ru: 'т', en: 't' }, exampleHangul: '끝', exampleTranscription: { ru: 'ккыт', en: 'kkeut' }, explanation: { ru: 'В конце слога оглушается до "т".', en: 'At the end of a syllable, it is pronounced as "t".' } },
    ], acceptablePronunciations: ['티읕', '타', '트'] },
    { hangul: 'ㅍ', name: '피읖', transcription: { ru: 'пх', en: 'p' }, type: 'consonant', soundVariations: [
        { position: { ru: 'В начале и середине слова', en: 'At the start and middle of a word' }, sound: { ru: 'пх', en: 'p' }, exampleHangul: '포도', exampleTranscription: { ru: 'пходо', en: 'podo' }, explanation: { ru: 'Придыхательный "пх". Произносится с сильным выдохом.', en: 'An aspirated "p" sound, pronounced with a strong puff of air.' } },
        { position: { ru: 'В конце слога (патчим)', en: 'At the end of a syllable (batchim)' }, sound: { ru: 'п', en: 'p' }, exampleHangul: '앞', exampleTranscription: { ru: 'ап', en: 'ap' }, explanation: { ru: 'В конце слога оглушается до "п".', en: 'At the end of a syllable, it is pronounced as "p".' } },
    ], acceptablePronunciations: ['피읖', '파', '프'] },
    { hangul: 'ㅎ', name: '히읗', transcription: { ru: 'х/т', en: 'h/t' }, type: 'consonant', soundVariations: [
        { position: { ru: 'В начале и середине слова', en: 'At the start and middle of a word' }, sound: { ru: 'х', en: 'h' }, exampleHangul: '하다', exampleTranscription: { ru: 'хада', en: 'hada' }, explanation: { ru: 'Легкий, слабый выдох, похожий на "х".', en: 'A light, weak "h" sound, like a sigh.' } },
        { position: { ru: 'В конце слога (патчим)', en: 'At the end of a syllable (batchim)' }, sound: { ru: 'т', en: 't' }, exampleHangul: '좋다', exampleTranscription: { ru: 'чотха', en: 'jota' }, explanation: { ru: 'В конце слога читается как "т", часто влияя на следующий согласный.', en: 'At the end of a syllable, it is pronounced as "t" and often affects the next consonant.' } },
    ], acceptablePronunciations: ['히읗', '하', '흐'] },
    { hangul: 'ㄲ', name: '쌍기역', transcription: { ru: 'кк', en: 'kk' }, type: 'consonant', soundVariations: [
        { position: { ru: 'Везде', en: 'Everywhere' }, sound: { ru: 'кк', en: 'kk' }, exampleHangul: '까치', exampleTranscription: { ru: 'ккачхи', en: 'kkachi' }, explanation: { ru: 'Напряженный, "взрывной" звук "к", без придыхания.', en: 'A tense, "explosive" "k" sound, without aspiration.' } },
    ], acceptablePronunciations: ['쌍기역', '까', '끄'] },
    { hangul: 'ㄸ', name: '쌍디귿', transcription: { ru: 'тт', en: 'tt' }, type: 'consonant', soundVariations: [
        { position: { ru: 'Везде', en: 'Everywhere' }, sound: { ru: 'тт', en: 'tt' }, exampleHangul: '따다', exampleTranscription: { ru: 'ттада', en: 'ttada' }, explanation: { ru: 'Напряженный "т", без придыхания.', en: 'A tense "t" sound, without aspiration.' } },
    ], acceptablePronunciations: ['쌍디귿', '따', '뜨'] },
    { hangul: 'ㅃ', name: '쌍비읍', transcription: { ru: 'пп', en: 'pp' }, type: 'consonant', soundVariations: [
        { position: { ru: 'Везде', en: 'Everywhere' }, sound: { ru: 'пп', en: 'pp' }, exampleHangul: '빵', exampleTranscription: { ru: 'ппанъ', en: 'ppang' }, explanation: { ru: 'Напряженный "п", без придыхания.', en: 'A tense "p" sound, without aspiration.' } },
    ], acceptablePronunciations: ['쌍비읍', '빠', '쁘'] },
    { hangul: 'ㅆ', name: '쌍시옷', transcription: { ru: 'сс', en: 'ss' }, type: 'consonant', soundVariations: [
        { position: { ru: 'Везде (кроме патчима)', en: 'Everywhere (except batchim)' }, sound: { ru: 'сс', en: 'ss' }, exampleHangul: '싸다', exampleTranscription: { ru: 'ссада', en: 'ssada' }, explanation: { ru: 'Напряженный "с". Перед ㅣ, ㅑ и т.д. не смягчается.', en: 'A tense "s" sound. Does not soften before vowels like ㅣ or ㅑ.' } },
        { position: { ru: 'В конце слога (патчим)', en: 'At the end of a syllable (batchim)' }, sound: { ru: 'т', en: 't' }, exampleHangul: '있다', exampleTranscription: { ru: 'итта', en: 'itta' }, explanation: { ru: 'В конце слога читается как "т".', en: 'At the end of a syllable, it is pronounced as "t".' } },
    ], acceptablePronunciations: ['쌍시옷', '싸', '쓰'] },
    { hangul: 'ㅉ', name: '쌍지읒', transcription: { ru: 'чч', en: 'jj' }, type: 'consonant', soundVariations: [
        { position: { ru: 'Везде', en: 'Everywhere' }, sound: { ru: 'чч', en: 'jj' }, exampleHangul: '짜다', exampleTranscription: { ru: 'ччада', en: 'jjada' }, explanation: { ru: 'Напряженный "ч", без придыхания.', en: 'A tense "j" sound, without aspiration.' } },
    ], acceptablePronunciations: ['쌍지읒', '짜', '쯔'] },
];
